# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_inside <- function(points) {
    .Call('_ptds2020hw4g0_is_inside', PACKAGE = 'ptds2020hw4g0', points)
}

